<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "employees"
 *
 * Auto generated by Extension Builder 2017-08-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'EmployeeList',
    'description' => 'List some employees',
    'category' => 'plugin',
    'author' => 'Alex Kellner',
    'author_email' => 'alexander.kellner@in2code.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
