<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cildb"
 *
 * Auto generated by Extension Builder 2019-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cil Daten Bank',
    'description' => 'Extension für Cil Datenbank',
    'category' => 'plugin',
    'author' => 'Cai He',
    'author_email' => 'che@bbaw.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'svconnector' =>'',
            'svconnector_sql' =>'',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
